<?php
/** Front page template. */
get_header();
$f = 'horn_free_theme_field';
$count = horn_free_theme_supporter_count( get_the_ID() );
$momentum_label = $f( 'momentum_label', 'People have added their voices' );
if ( 'Indians have added their voice' === trim( $momentum_label ) ) {
	$momentum_label = 'People have added their voices';
}
$image = $f( 'hero_image' );
$image_url = is_array( $image ) && ! empty( $image['url'] ) ? $image['url'] : get_template_directory_uri() . '/assets/images/home%201.png';
$image_alt = is_array( $image ) && ! empty( $image['alt'] ) ? $image['alt'] : __( 'Children walking beside a truck on an Indian street.', 'horn-free-theme' );
?>
<main id="main">
<section class="hero"><div class="container hero-inner"><div class="hero-content">
<p class="eyebrow"><?php echo esc_html( $f( 'hero_eyebrow', 'A citizen movement for a quieter India' ) ); ?></p>
<h1 class="hero-title"><?php echo wp_kses_post( $f( 'hero_title', 'From <span class="loud">Blow Horn</span> to <span class="calm">Om Shanti</span>' ) ); ?></h1>
<p class="hero-sub"><?php echo wp_kses_post( nl2br( $f( 'hero_text', 'India gave the world the word for peace — शांति. Yet every truck on our roads still orders us to Blow Horn. We’re here to change what our roads say, and how they sound.' ) ) ); ?></p>
<div class="hero-actions"><a class="btn btn-primary" href="#action"><?php echo esc_html( $f( 'hero_primary_label', 'Join the movement' ) ); ?></a><a class="btn btn-ghost" href="#problem"><?php echo esc_html( $f( 'hero_secondary_label', 'See why it matters' ) ); ?></a></div>
<p class="trust-microline"><?php echo esc_html( $f( 'hero_trust', 'No donations. No politics. We will never ask you for money — only for your voice.' ) ); ?></p>
</div><figure class="hero-media"><img src="<?php echo esc_url( $image_url ); ?>" alt="<?php echo esc_attr( $image_alt ); ?>"></figure></div></section>

<section class="section" id="problem"><div class="container narrow reveal"><h2 class="section-title"><?php echo esc_html( $f( 'problem_title', 'Our roads are loud, and it’s costing us more than our calm.' ) ); ?></h2><p class="lede"><?php echo wp_kses_post( nl2br( $f( 'problem_intro', 'Constant honking isn’t just noise. It’s a daily assault on our hearing, our nerves, and our cities — and it’s so normal we’ve stopped noticing.' ) ) ); ?></p></div>
<div class="container stats reveal"><?php for ( $i=1; $i<=3; $i++ ) : $nums=array('80–120 dB','1.5 lakh+ deaths','Every day'); $texts=array('A single truck horn. The safe limit for a residential street is 55 dB.','Lives lost on Indian roads every year. Roads this dangerous shouldn’t also be this hostile.','Millions of trucks pass schools, hospitals and homes carrying the words Blow Horn.'); $stat_number = $f( 'stat_'.$i.'_number', $nums[$i-1] ); if ( 2 === $i && '1.5 lakh+' === trim( $stat_number ) ) { $stat_number = '1.5 lakh+ deaths'; } ?><div class="stat"><span class="stat-num"><?php echo esc_html( $stat_number ); ?></span><p class="stat-copy"><?php echo wp_kses_post( nl2br( $f( 'stat_'.$i.'_text', $texts[$i-1] ) ) ); ?></p></div><?php endfor; ?></div>
</section>

<section class="section section-dark" id="action"><div class="container narrow reveal"><h2 class="section-title"><?php echo esc_html( $f( 'action_title', 'Here’s the whole movement, in three minutes.' ) ); ?></h2><p class="lede lede-light"><?php echo esc_html( $f( 'action_intro', 'No marches. No money. Three steps from your phone.' ) ); ?></p></div><div class="container action-flow reveal">
<div class="step" id="step-1"><div class="step-head"><span class="step-num">1</span><h3><?php echo esc_html( $f( 'action_step_1_title', 'Add your name' ) ); ?></h3></div><p class="step-copy"><?php echo esc_html( $f( 'action_step_1_text', 'Tell us who you are and where you’re from. Your name joins a public count we put in front of the government.' ) ); ?></p><form class="join-form" id="join-form" novalidate><div class="field-row"><div class="field"><label for="f-name">Full Name</label><input id="f-name" name="name" type="text" autocomplete="name" required></div><div class="field"><label for="f-state">State</label><input id="f-state" name="state" type="text" autocomplete="address-level1" required></div></div><div class="field-row"><div class="field"><label for="f-country">Country</label><select id="f-country" name="country" autocomplete="country" required><option value="">Select country</option><?php foreach ( horn_free_theme_countries() as $country_code => $country_name ) : ?><option value="<?php echo esc_attr( $country_code ); ?>" <?php selected( $country_code, 'IN' ); ?>><?php echo esc_html( $country_name ); ?></option><?php endforeach; ?></select></div><div class="field"><label for="f-email">Email</label><input id="f-email" name="email" type="email" autocomplete="email" required></div></div><button class="btn btn-primary btn-block" type="submit">Count me in</button><p class="form-error" id="form-error" role="alert" hidden></p></form></div>
<div class="step step-locked" id="step-2" aria-hidden="true"><div class="step-head"><span class="step-num">2</span><h3><?php echo esc_html( $f( 'action_step_2_title', 'Email the Ministry' ) ); ?></h3></div><p class="step-copy"><?php echo esc_html( $f( 'action_step_2_text', 'One tap fills in a respectful message to the Ministry of Road Transport & Highways.' ) ); ?></p><a class="btn btn-primary btn-block" id="email-btn" data-to="nitin.gadkari@nic.in" href="#">Send my email</a></div>
<div class="step step-locked" id="step-3" aria-hidden="true"><div class="step-head"><span class="step-num">3</span><h3><?php echo esc_html( $f( 'action_step_3_title', 'Bring three friends' ) ); ?></h3></div><p class="step-copy"><?php echo esc_html( $f( 'action_step_3_text', 'Forward this to three people who would want a quieter India.' ) ); ?></p><a class="btn btn-whatsapp btn-block" id="share-btn" href="#" target="_blank" rel="noopener">Share on WhatsApp</a></div></div><div class="container narrow reveal"><p class="closing-line closing-light"><?php echo esc_html( $f( 'action_closing', 'That’s all. No fee, no form-filling marathon, no catch. Just your voice, counted.' ) ); ?></p></div></section>

<div class="email-dialog" id="email-dialog" role="dialog" aria-modal="true" aria-labelledby="email-dialog-title" hidden><div class="email-dialog-backdrop" data-email-close></div><div class="email-dialog-panel" role="document"><button class="email-dialog-close" type="button" data-email-close aria-label="Close">×</button><p class="eyebrow">Choose how to send</p><h2 id="email-dialog-title">Send from your own email account</h2><p>We’ll open a new message with the recipient, subject and body already filled in.</p><div class="email-dialog-options"><button class="btn btn-primary email-option-gmail" type="button" data-email-method="gmail">Open in Gmail</button><button class="btn btn-ghost" type="button" data-email-method="outlook">Open in Outlook</button><button class="btn btn-ghost email-option-default" type="button" data-email-method="default">Open email app</button><button class="btn btn-ghost" type="button" data-email-method="copy">Copy email message</button></div><p class="email-dialog-status" id="email-dialog-status" role="status" aria-live="polite"></p></div></div>

<section class="section section-tint" id="ask"><div class="container narrow reveal"><h2 class="section-title"><?php echo esc_html( $f( 'ask_title', 'We’re not asking for silence. We’re asking for three words to change.' ) ); ?></h2><p class="lede"><?php echo wp_kses_post( nl2br( $f( 'ask_intro', 'For decades, India’s commercial vehicles have carried signage that invites honking. Our ask is simple: replace that signage with a message that asks for the opposite.' ) ) ); ?></p></div>
<div class="container ask-cards reveal"><div class="ask-card"><span><?php echo esc_html( $f( 'ask_card_1', 'Stop Horn' ) ); ?></span></div><div class="ask-card"><span><?php echo esc_html( $f( 'ask_card_2', 'No Horn' ) ); ?></span></div><div class="ask-card ask-card--accent"><span><?php echo esc_html( $f( 'ask_card_3', 'Om Shanti' ) ); ?></span><small><?php echo esc_html( $f( 'ask_card_3_note', 'peace, for the road' ) ); ?></small></div></div><div class="container narrow reveal"><p class="closing-line"><?php echo esc_html( $f( 'ask_closing', 'One change, on the back of every truck. From a command to honk — to a reminder to breathe.' ) ); ?></p></div></section>

<section class="section" id="proof"><div class="container narrow reveal proof-block"><h2 class="section-title"><?php echo esc_html( $f( 'proof_title', 'This isn’t a dream. It’s already been done once.' ) ); ?></h2><p class="lede"><?php echo wp_kses_post( nl2br( $f( 'proof_text', 'In 2015, Maharashtra’s Transport Commissioner ordered “Horn OK Please” removed from commercial vehicles across the state — with a single administrative circular.' ) ) ); ?></p><p class="punchline"><?php echo wp_kses_post( nl2br( $f( 'proof_punchline', 'If one state can do it with the stroke of a pen, the country can too. We just have to ask — together.' ) ) ); ?></p></div></section>

<section class="section section-tint" id="momentum"><div class="container narrow reveal momentum"><h2 class="section-title"><?php echo esc_html( $f( 'momentum_title', 'You’d be joining a movement that’s already moving.' ) ); ?></h2><p class="big-counter"><span data-counter data-target="<?php echo esc_attr( $count ); ?>"><?php echo esc_html( number_format_i18n( $count ) ); ?></span></p><p class="counter-label"><?php echo esc_html( $momentum_label ); ?></p><figure class="voices" data-voices="<?php echo esc_attr( wp_json_encode( array( array('q'=>$f('voice_quote_1','I forgot what quiet sounds like. I want it back.'),'a'=>$f('voice_author_1','— A supporter')), array('q'=>$f('voice_quote_2','My daughter covers her ears every morning on the way to school.'),'a'=>$f('voice_author_2','— A parent')), array('q'=>$f('voice_quote_3','I drive a truck. I never wanted my work to be the loudest thing on the street.'),'a'=>$f('voice_author_3','— A driver')) ) ) ); ?>"><blockquote id="voice-quote">“<?php echo esc_html( $f( 'voice_quote_1', 'I forgot what quiet sounds like. I want it back.' ) ); ?>”</blockquote><figcaption id="voice-author"><?php echo esc_html( $f( 'voice_author_1', '— A supporter' ) ); ?></figcaption></figure></div></section>

<section class="section" id="story"><div class="container narrow reveal"><h2 class="section-title"><?php echo esc_html( $f( 'story_title', 'Who’s behind this?' ) ); ?></h2><p class="lede"><?php echo wp_kses_post( nl2br( $f( 'story_text', 'Horn Free India is a citizen movement. We are not an NGO, not a company, and not tied to any political party.' ) ) ); ?></p><ul class="promises"><?php for($i=1;$i<=3;$i++): $defaults=array('We never take money. The only thing we collect is voices.','We’re non-partisan. This is about peace and safety, not politics.','We’re real and reachable.'); ?><li><?php echo wp_kses_post( nl2br( $f( 'promise_'.$i, $defaults[$i-1] ) ) ); ?></li><?php endfor; ?></ul></div></section>
<section class="section section-dark closing-cta" id="spread"><div class="container narrow reveal"><h2 class="section-title"><?php echo wp_kses_post( $f( 'closing_title', 'India said <span class="calm">Om Shanti</span> to the world. It’s time our streets said it too.' ) ); ?></h2><p class="lede lede-light"><?php echo esc_html( $f( 'closing_text', 'It costs you nothing but a name and three minutes.' ) ); ?></p><a class="btn btn-primary" href="#action"><?php echo esc_html( $f( 'closing_button', 'Join the movement' ) ); ?></a></div></section>
</main>
<?php get_footer(); ?>
